"use client";

import { Sparkles, BarChart3 } from 'lucide-react';

/**
 * Summary of what reviewers actually said. The copy is computed server-side
 * from the review rows themselves (see AIService::extractiveSummary), so it
 * reflects negative feedback too. It's only labelled "AI generated" when a
 * model actually produced it.
 */
export default function AIReviewSummary({ summary, isAiGenerated = false, total = 0 }) {
  if (!summary || total === 0) return null;

  return (
    <div className="bg-gradient-to-br from-accent-soft to-accent-soft border border-accent p-6 rounded-panel relative overflow-hidden">
      <div className="absolute -top-6 -right-6 text-accent/10" aria-hidden="true">
        <Sparkles size={120} />
      </div>

      <div className="flex items-center gap-2 mb-3">
        {isAiGenerated ? (
          <Sparkles className="w-4 h-4 text-accent" />
        ) : (
          <BarChart3 className="w-4 h-4 text-accent" />
        )}
        <h3 className="text-xs font-black text-accent uppercase tracking-wider">
          {isAiGenerated ? 'AI Review Summary' : 'What reviewers say'}
        </h3>
      </div>

      <p className="text-ink leading-relaxed relative z-10 font-medium">
        {summary}
      </p>

      <p className="mt-4 text-[11px] text-ink-subtle relative z-10">
        {isAiGenerated
          ? `Generated by AI from ${total} verified buyer ${total === 1 ? 'review' : 'reviews'}.`
          : `Computed directly from ${total} verified buyer ${total === 1 ? 'review' : 'reviews'} — no AI model involved.`}
      </p>
    </div>
  );
}
