/**
 * Token generator. Reads src/tokens.js and writes every consumable form into
 * dist/. Run with `npm run tokens:build`.
 *
 * This script existing is the point: before it, the palette lived in
 * lib/designTokens.js, again in the :root block of globals.css, and a third
 * time in tailwind.config.js — three hand-synced copies that had already
 * drifted. Now there is one copy and the rest are build output.
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, 'dist');

const T = require('./src/tokens.js');

const BANNER = `/* GENERATED by packages/tokens/build.mjs — do not edit.
   Edit packages/tokens/src/tokens.js and run \`npm run tokens:build\`. */`;

const light = (pair) => (Array.isArray(pair) ? pair[0] : pair);
const dark = (pair) => (Array.isArray(pair) ? pair[1] : pair);

// ─── tokens.css ──────────────────────────────────────────────────────────────
// Fonts ship as a <link> href rather than a CSS @import. An @import inside this
// stylesheet would be inlined *after* Tailwind's expanded output, which is
// invalid CSS (imports must precede all rules) and takes the whole sheet down;
// a <link> also avoids the request waterfall an @import chain creates.
function fontsHref() {
  const families = T.fontsToLoad
    .map((f) => `family=${f.family.replace(/ /g, '+')}:wght@${f.weights}`)
    .join('&');

  return `https://fonts.googleapis.com/css2?${families}&display=swap`;
}

/** `[x, y, blur, spread, r, g, b, a]` -> a CSS box-shadow value. */
function shadowToCss(layers) {
  return layers
    .map(([x, y, blur, spread, r, g, b, a]) =>
      `${x}px ${y}px ${blur}px ${spread}px rgba(${r},${g},${b},${a})`)
    .join(', ');
}

function buildCss() {
  const lines = [BANNER, ''];

  // Light values
  lines.push(':root {');
  for (const [name, pair] of Object.entries(T.color)) lines.push(`  --ds-${name}: ${light(pair)};`);
  for (const [name, sh] of Object.entries(T.shadow)) lines.push(`  --ds-shadow-${name}: ${shadowToCss(sh.light)};`);
  lines.push('');
  for (const [name, value] of Object.entries(T.radius)) lines.push(`  --ds-radius-${name}: ${value};`);
  for (const [name, value] of Object.entries(T.font)) lines.push(`  --ds-font-${name}: ${value};`);
  for (const [name, value] of Object.entries(T.motion)) lines.push(`  --ds-motion-${name}: ${value};`);
  for (const [name, value] of Object.entries(T.z)) lines.push(`  --ds-z-${name}: ${value};`);
  lines.push('}', '');

  // Dark overrides. Only colour and shadow flip; geometry and type do not.
  lines.push('.dark {');
  for (const [name, pair] of Object.entries(T.color)) lines.push(`  --ds-${name}: ${dark(pair)};`);
  for (const [name, sh] of Object.entries(T.shadow)) lines.push(`  --ds-shadow-${name}: ${shadowToCss(sh.dark)};`);
  lines.push('}', '');

  // Tailwind v4 theme. `inline` makes each utility emit var(--ds-*) rather than
  // the resolved literal, which is precisely what lets the .dark block above
  // retheme every utility without a single `dark:` variant in the components.
  lines.push('@theme inline {');
  for (const name of Object.keys(T.color)) lines.push(`  --color-${name}: var(--ds-${name});`);
  lines.push('');
  for (const name of Object.keys(T.radius)) lines.push(`  --radius-${name}: var(--ds-radius-${name});`);
  lines.push('');
  for (const name of Object.keys(T.shadow)) lines.push(`  --shadow-${name}: var(--ds-shadow-${name});`);
  lines.push('');
  for (const name of Object.keys(T.font)) lines.push(`  --font-${name}: var(--ds-font-${name});`);
  lines.push('');
  for (const [name, [size, lh]] of Object.entries(T.text)) {
    lines.push(`  --text-${name}: ${size};`);
    lines.push(`  --text-${name}--line-height: ${lh};`);
  }
  lines.push('');
  for (const name of Object.keys(T.z)) lines.push(`  --z-index-${name}: var(--ds-z-${name});`);
  lines.push('}', '');

  return lines.join('\n');
}

// ─── tokens.js / tokens.json ─────────────────────────────────────────────────
// Resolved light-mode values, for code that needs a colour outside CSS
// (canvas rendering, meta theme-color, chart series, emailed HTML).
function resolved() {
  const flat = (obj, fn) => Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, fn(v)]));
  return {
    color: flat(T.color, light),
    colorDark: flat(T.color, dark),
    shadow: Object.fromEntries(Object.entries(T.shadow).map(([k, v]) => [k, shadowToCss(v.light)])),
    radius: T.radius,
    font: T.font,
    fontFamily: T.fontFamily,
    text: T.text,
    weight: T.weight,
    space: T.space,
    motion: T.motion,
    z: T.z,
    fontsHref: fontsHref(),
  };
}

function buildJs() {
  const r = resolved();
  return (
    `${BANNER}\n` +
    `export const tokens = ${JSON.stringify(r, null, 2)};\n` +
    `export const fontsHref = ${JSON.stringify(r.fontsHref)};\n` +
    `export default tokens;\n`
  );
}

// ─── tokens.dart ─────────────────────────────────────────────────────────────
// The Flutter app consumes the same source, so a palette change lands on web
// and mobile from one edit instead of being re-keyed by hand. This emits a
// `DsColors` *instance* class with light/dark constants rather than two static
// classes, so the Flutter side can hold "the palette for the current theme" in
// one variable and hand it around — the direct analogue of a CSS variable
// flipping under `.dark`.
function buildDart() {
  // Dart reserved words can't be identifiers. `new` is a real token name, so
  // rather than renaming it in the source (and desyncing it from the CSS
  // variable and the Tailwind utility) it is suffixed only on the Dart side.
  const DART_RESERVED = new Set([
    'new', 'class', 'is', 'in', 'if', 'else', 'for', 'while', 'switch', 'case',
    'default', 'return', 'void', 'null', 'true', 'false', 'this', 'super',
    'const', 'final', 'var', 'static', 'enum', 'extends', 'with', 'try', 'catch',
  ]);

  const camel = (s) => {
    const c = s.replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());
    return DART_RESERVED.has(c) ? `${c}Color` : c;
  };
  const hexToDart = (hex) => `Color(0xFF${String(hex).replace('#', '').toUpperCase()})`;

  const names = Object.keys(T.color);

  const fields = names.map((n) => `  final Color ${camel(n)};`).join('\n');
  const ctorArgs = names.map((n) => `    required this.${camel(n)},`).join('\n');
  const instance = (pick) =>
    names.map((n) => `    ${camel(n)}: ${hexToDart(pick(T.color[n]))},`).join('\n');

  const shadowLayers = (layers) =>
    layers
      .map(
        ([x, y, blur, spread, r, g, b, a]) =>
          `      BoxShadow(color: Color.fromRGBO(${r}, ${g}, ${b}, ${a}), offset: Offset(${x}, ${y}), blurRadius: ${blur}, spreadRadius: ${spread}),`,
      )
      .join('\n');

  const shadowFields = Object.keys(T.shadow)
    .map((n) => `  final List<BoxShadow> ${camel(n)};`)
    .join('\n');
  const shadowCtor = Object.keys(T.shadow)
    .map((n) => `    required this.${camel(n)},`)
    .join('\n');
  // No inner `const` — these are emitted inside a `static const` initialiser,
  // where it is redundant and trips the analyzer's unnecessary_const lint.
  const shadowInstance = (mode) =>
    Object.entries(T.shadow)
      .map(([n, v]) => `    ${camel(n)}: [\n${shadowLayers(v[mode])}\n    ],`)
      .join('\n');

  // rem -> logical pixels. The web scale is authored in rem against a 16px
  // root, and Flutter's logical pixel is the same reference unit, so the
  // conversion is exact rather than an eyeballed match.
  const rem = (v) => (parseFloat(v) * 16).toFixed(2).replace(/\.00$/, '');

  return `// GENERATED by packages/tokens/build.mjs — do not edit.
// Edit packages/tokens/src/tokens.js and run \`npm run tokens:build\`.
//
// The web app reads the same source through CSS custom properties; this file is
// the Flutter projection of it. Nothing here is hand-maintained.
import 'package:flutter/material.dart';

/// Every semantic colour, for one theme. Held by DsTheme and passed down, so a
/// widget asks for \`ds.colors.surface\` the way the web asks for \`bg-surface\`.
@immutable
class DsColors {
${fields}

  const DsColors({
${ctorArgs}
  });

  static const light = DsColors(
${instance(light)}
  );

  static const dark = DsColors(
${instance(dark)}
  );
}

@immutable
class DsShadows {
${shadowFields}

  const DsShadows({
${shadowCtor}
  });

  static const light = DsShadows(
${shadowInstance('light')}
  );

  static const dark = DsShadows(
${shadowInstance('dark')}
  );
}

/// Radii, named by role rather than size — same rule as the web.
class DsRadius {
${Object.entries(T.radius).map(([k, v]) => `  static const double ${camel(k)} = ${parseFloat(v)};`).join('\n')}

${Object.entries(T.radius).map(([k, v]) => `  static const BorderRadius ${camel(k)}All = BorderRadius.all(Radius.circular(${parseFloat(v)}));`).join('\n')}
}

/// Spacing scale in logical pixels.
class DsSpace {
${Object.entries(T.space).map(([k, v]) => `  static const double s${k} = ${v};`).join('\n')}
}

/// Type scale. \`size\` is the font size, \`height\` the Flutter line-height
/// multiplier (CSS line-height / font-size).
class DsText {
${Object.entries(T.text)
  .map(([k, [size, lh]]) => {
    const name = camel(k.replace(/^(\d)/, 'x$1'));
    const h = (parseFloat(lh) / parseFloat(size)).toFixed(3);
    return `  static const double ${name} = ${rem(size)};\n  static const double ${name}Height = ${h};`;
  })
  .join('\n')}
}

class DsWeight {
${Object.entries(T.weight).map(([k, v]) => `  static const FontWeight ${k} = FontWeight.w${v};`).join('\n')}
}

class DsFont {
${Object.entries(T.fontFamily).map(([k, v]) => `  static const String ${k} = '${v}';`).join('\n')}
}

class DsMotion {
${Object.entries(T.motion)
  .filter(([, v]) => /ms$/.test(v))
  .map(([k, v]) => `  static const Duration ${k} = Duration(milliseconds: ${parseInt(v, 10)});`)
  .join('\n')}

  static const Curve ease = Curves.easeInOut;
  static const Curve spring = Curves.easeOutBack;
}
`;
}

// ─── brand.dart ──────────────────────────────────────────────────────────────
// Brand identity, projected for Flutter from packages/brand. Same reason as the
// colours: two copies of a legal entity name is one copy too many.
async function buildBrandDart() {
  // packages/brand is plain ESM with no JSX or bundler-only syntax, so it can
  // be imported straight into this script. Reading the real exported object
  // beats scraping the source for string literals — a value in a template
  // literal or a computed field would silently come out empty.
  const { getBrand } = await import(pathToFileURL(join(here, '..', 'brand', 'index.js')).href);
  const b = getBrand();

  const dartString = (v) => `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;

  const scalars = Object.entries(b).filter(([, v]) => typeof v === 'string');

  const links = (b.footerLinks || [])
    .map((l) => `    (label: ${dartString(l.label)}, href: ${dartString(l.href)}),`)
    .join('\n');

  return `// GENERATED by packages/tokens/build.mjs from packages/brand/index.js — do not edit.
//
// Brand identity, projected for Flutter. Same reason as the colours: a second
// hand-maintained copy of a legal entity name is one copy too many.
class DsBrand {
${scalars.map(([k, v]) => `  static const String ${k} = ${dartString(v)};`).join('\n')}

  /// Namespaced key, matching the web client's localStorage convention so the
  /// two never collide when both are pointed at the same account.
  static String storageKey(String name) => '\${storageNamespace}_$name';

  static const List<({String label, String href})> legalLinks = [
${links}
  ];
}
`;
}

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'tokens.css'), buildCss());
writeFileSync(join(dist, 'tokens.js'), buildJs());
writeFileSync(join(dist, 'tokens.json'), JSON.stringify(resolved(), null, 2));
writeFileSync(join(dist, 'tokens.dart'), buildDart());

// Written straight into the Flutter app so `npm run tokens:build` updates both
// clients. A stale copy in dist/ that someone has to remember to sync would
// reintroduce exactly the drift this package removed.
const flutterDesign = join(here, '..', '..', 'marketplace_app', 'lib', 'design');
if (existsSync(join(here, '..', '..', 'marketplace_app'))) {
  mkdirSync(flutterDesign, { recursive: true });
  writeFileSync(join(flutterDesign, 'tokens.g.dart'), buildDart());
  writeFileSync(join(flutterDesign, 'brand.g.dart'), await buildBrandDart());
  console.log('tokens: wrote marketplace_app/lib/design/{tokens,brand}.g.dart');
}

console.log('tokens: wrote dist/tokens.{css,js,json,dart}');
